title = "Memento"
feed_filename = "rss.xml"
base_url = "http://leiserfg.github.io"
theme = "DeepThought"
default_language = "en"

highlight_code = true
highlight_theme = "one-dark"
generate_feed = true
compile_sass = true
build_search_index = true


[extra]

navbar_items = [
	# { url = "$BASE_URL/", name = "Home" },
	# { url = "$BASE_URL/posts", name = "Posts" },
	# { url = "$BASE_URL/docs", name = "Docs" },
	# { url = "$BASE_URL/tags", name = "Tags" },
	# { url = "$BASE_URL/categories", name = "Categories" },
]

[extra.social]
github = "leiserfg"
linkedin = "leiserfg"
twitter = "leiserfg"
